export const schemaFields = {
  announcement: [
    "id",
    "name",
    "description",
    "image",
    "createdAt",
    "updatedAt",
  ],
  assignCourseTeacher: [
    "id",
    "createdAt",
    "updatedAt",
    "teacherId",
    "sectionId",
    "courseId",
  ],
  assignTeacher: ["id", "createdAt", "updatedAt", "teacherId", "sectionId"],
  consultation: [
    "id",
    "concern",
    "comment",
    "status",
    "createdAt",
    "updatedAt",
    "teacherId",
    "studentNumber",
    "courseId",
  ],
  courses: [
    "id",
    "name",
    "code",
    "unit",
    "prerequisite",
    "isArchive",
    "createdAt",
    "updatedAt",
  ],
  documentRequest: [
    "id",
    "typeDocument",
    "purpose",
    "status",
    "createdAt",
    "updatedAt",
    "studentNumber",
  ],
  feedback: ["id", "name", "feedback", "comment", "createdAt", "updatedAt"],
  grades: [
    "id",
    "studentNumber",
    "courseCode",
    "programCode",
    "sectionName",
    "period",
    "grade",
    "remarks",
    "createdAt",
    "updatedAt",
  ],
  logs: ["id", "action", "createdAt", "updatedAt"],
  programs: ["id", "name", "code", "isArchive", "createdAt", "updatedAt"],
  sections: [
    "id",
    "name",
    "isArchive",
    "createdAt",
    "updatedAt",
    "yearLevelId",
    "programId",
  ],
  students: [
    "id",
    "studentNumber",
    "firstName",
    "middleName",
    "lastName",
    "extensionName",
    "birthDate",
    "age",
    "gender",
    "civilStatus",
    "phoneNumber",
    "region",
    "province",
    "city",
    "barangay",
    "houseNumber",
    "zipCode",
    "email",
    "password",
    "profileImage",
    "isArchive",
    "isAuthenticate",
    "otpSecret",
    "otpQrCode",
    "elementarySchool",
    "highSchool",
    "createdAt",
    "updatedAt",
    "yearLevelId",
    "programId",
    "sectionId",
  ],
  teachers: [
    "id",
    "employeeId",
    "firstName",
    "middleName",
    "lastName",
    "extensionName",
    "birthDate",
    "age",
    "gender",
    "civilStatus",
    "phoneNumber",
    "region",
    "province",
    "city",
    "barangay",
    "houseNumber",
    "zipCode",
    "email",
    "password",
    "profileImage",
    "isArchive",
    "position",
    "createdAt",
    "updatedAt",
    "programId",
  ],
  support: [
    "id",
    "email",
    "name",
    "concerns",
    "attachment",
    "status",
    "createdAt",
    "updatedAt",
  ],
  uploadedEcr: ["id", "teacherId", "name", "createdAt", "updatedAt"],
  yearLevels: ["id", "name", "createdAt", "updatedAt"],
};
